name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Angular
      run: npm install -g @angular/cli@latest

    - name: Install Requirements
      run: npm install .

    - name: Build Dist
      run: ./build-dist.py

    - name: Lint
      run: ng lint
